### ISSUE TITLE
jdc --help显示的sub-commands应描述所操作的资源。比如mps表示什么意思？可以是汉字。

### ISSUE THREAD

**Issue by obsicn** [jdcloud-api/jdcloud-cli#22]
$  jdc --help

sub-commands:
  {mps,cps,rds,jke,vpc,xdata,mongodb,configure,streambus,ipanti,baseanti,datastar,redis,nc,monitor,iam,disk,cr,streamcomputer,sop,clouddnsservice,vm,oss}
    mps                 使用该子命令操作mps相关资源
    cps                 使用该子命令操作cps相关资源
    rds                 使用该子命令操作rds相关资源
    jke                 使用该子命令操作jke相关资源
    vpc                 使用该子命令操作vpc相关资源
    xdata               使用该子命令操作xdata相关资源
    mongodb             使用该子命令操作mongodb相关资源
    configure           使用该子命令配置CLI
    streambus           使用该子命令操作streambus相关资源
    ipanti              使用该子命令操作ipanti相关资源
    baseanti            使用该子命令操作baseanti相关资源
    datastar            使用该子命令操作datastar相关资源
    redis               使用该子命令操作redis相关资源
    nc                  使用该子命令操作nc相关资源
    monitor             使用该子命令操作monitor相关资源
    iam                 使用该子命令操作iam相关资源
    disk                使用该子命令操作disk相关资源
    cr                  使用该子命令操作cr相关资源
    streamcomputer      使用该子命令操作streamcomputer相关资源
    sop                 使用该子命令操作sop相关资源
    clouddnsservice     使用该子命令操作clouddnsservice相关资源
    vm                  使用该子命令操作vm相关资源
    oss                 使用该子命令操作oss相关资源
MichaeldeMacBook-Pro-2:~ myang

**Comment by oulinbao** [comment]
在0.7.2中已优化
