### ISSUE TITLE
vm create-instances命令中instance-spec是否应为可选参数？

### ISSUE THREAD

**Issue by obsicn** [jdcloud-api/jdcloud-cli#23]
如果instance-spec是必选参数，那如果有-input-json参数，以哪个参数的配置信息为准？

MichaeldeMacBook-Pro-2:~ myang$ jdc vm create-instances --help
usage: jdc vm create-instances [-h] [--region-id REGIONID] --instance-spec
                               INSTANCESPEC [--max-count MAXCOUNT]
                               [--client-token CLIENTTOKEN]
                               [--input-json INPUT_JSON] [--headers HEADERS]

**Comment by oulinbao** [comment]
instance-spec 在业务上是必选的，和input-json的冲突问题在v1.0.0解决了。
